// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiSJCS2ZaeMIrl1ByrH6wrGE4i08jMHqo',
    appId: '1:774829085854:web:345165bcd09555e581178f',
    messagingSenderId: '774829085854',
    projectId: 'real-time-chat-app-dcab2',
    authDomain: 'real-time-chat-app-dcab2.firebaseapp.com',
    storageBucket: 'real-time-chat-app-dcab2.firebasestorage.app',
    measurementId: 'G-HPHJEQVVCR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMAiZQTiFfEclXuRTs6aKRqMcOzivrC6I',
    appId: '1:774829085854:android:bc57a7b896d9a35d81178f',
    messagingSenderId: '774829085854',
    projectId: 'real-time-chat-app-dcab2',
    storageBucket: 'real-time-chat-app-dcab2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHMTbhHdXqk-yIBKSMePaI91l-QOtwSm8',
    appId: '1:774829085854:ios:3f564d48bb3f867981178f',
    messagingSenderId: '774829085854',
    projectId: 'real-time-chat-app-dcab2',
    storageBucket: 'real-time-chat-app-dcab2.firebasestorage.app',
    iosBundleId: 'com.example.realTimeChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHMTbhHdXqk-yIBKSMePaI91l-QOtwSm8',
    appId: '1:774829085854:ios:3f564d48bb3f867981178f',
    messagingSenderId: '774829085854',
    projectId: 'real-time-chat-app-dcab2',
    storageBucket: 'real-time-chat-app-dcab2.firebasestorage.app',
    iosBundleId: 'com.example.realTimeChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiSJCS2ZaeMIrl1ByrH6wrGE4i08jMHqo',
    appId: '1:774829085854:web:d55f708308c196c781178f',
    messagingSenderId: '774829085854',
    projectId: 'real-time-chat-app-dcab2',
    authDomain: 'real-time-chat-app-dcab2.firebaseapp.com',
    storageBucket: 'real-time-chat-app-dcab2.firebasestorage.app',
    measurementId: 'G-4QZPT9R253',
  );
}
